### ISSUE TITLE
训练暂停

### ISSUE THREAD

**Issue by ziaow116** [MikeWangWZHL/PAPO#15]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00, 12.67it/s]
(WorkerDict pid=1117909) You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
(WorkerDict pid=1117657) [rank0]:[W910 16:17:43.850911918 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
(WorkerDict pid=1117657) NCCL version 2.21.5+cuda12.4
(WorkerDict pid=1117657) Qwen2_5_VLForConditionalGeneration contains 3.75B parameters.
(WorkerDict pid=1117657) After huggingface model init: 0.74 GB / 79.10 GB.
(WorkerDict pid=1117657) FSDP wrap policy: functools.partial(<function transformer_auto_wrap_policy at 0x740cb30029e0>, transformer_layer_cls={<class 'transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLVisionBlock'>, <class 'transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLDecoderLayer'>}).
(WorkerDict pid=1117657) After FSDP module init: 5.89 GB / 79.10 GB.
(WorkerDict pid=1117657) After optimizer init: 5.89 GB / 79.10 GB.
(WorkerDict pid=1117657) After offload actor model during init: 0.75 GB / 79.10 GB.
(WorkerDict pid=1117657) After offload actor optimizer during init: 0.75 GB / 79.10 GB.
(WorkerDict pid=1117657) Ulysses patch applied!
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
(WorkerDict pid=1117909) [W910 16:17:41.514627458 Utils.hpp:136] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  8.21it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00, 12.65it/s]
(WorkerDict pid=1117657) Qwen2_5_VLForConditionalGeneration contains 3.75B parameters.
(WorkerDict pid=1117657) After huggingface model init: 0.75 GB / 79.10 GB.
(WorkerDict pid=1117657) FSDP wrap policy: functools.partial(<function transformer_auto_wrap_policy at 0x740cb30029e0>, transformer_layer_cls={<class 'transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLVisionBlock'>, <class 'transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLDecoderLayer'>}).
(WorkerDict pid=1117657) After FSDP module init: 2.77 GB / 79.10 GB.
(WorkerDict pid=1117657) WARNING 09-10 16:17:59 [utils.py:2444] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7409102edf90>
(WorkerDict pid=1117657) Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
(WorkerDict pid=1117909) [rank1]:[W910 16:17:43.882662368 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 1]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
(WorkerDict pid=1117909) WARNING 09-10 16:18:04 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
(WorkerDict pid=1117909) WARNING 09-10 16:18:00 [utils.py:2444] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7844044aaa40>
(WorkerDict pid=1117657) [rank0]:[W910 16:18:30.473799069 CUDAGraph.cpp:133] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
(WorkerDict pid=1117909) Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

你好作者，我对Qwen2.5-VL 3B进行grpo训练，但是一直卡在这里，有什么方法可以解决吗。如果您回复，我将感激不尽！

**Comment by TigerLHH** [comment]
> 您好作者，我已经解决了上述的问题，同时谢谢您的回复。但是我还想知道您提出的隐式感知损失和mask策略的想法有文章可以参考吗，我非常需要这些文章。如果您回复，我将感激不尽！

你好，我也遇到了相同的问题，训练卡住无法推进，也没有报错，能分享一下如何解决的吗
